### ISSUE TITLE
Setup Development and Production Environment for Workflow

### ISSUE THREAD

**Issue by BigSamu** [BigSamu/OpenSearch_Changelog_Workflow#43]
Currently the workflow has the URL for the Github Domain fixed to the deployment domain as follows:

```js
export const GITHUB_APP_DOMAIN = "https://open-search-changeset-bot.vercel.app";
```

For development, each contributor has to change that URL with a tunnel service (for instance, [ngrok](https://ngrok.com/)) to be able to contribute in the [GitHub App](https://github.com/BigSamu/OpenSearch_Changeset_Bot).

A solution to this problem is to setup this constant as an environmental variable in the `.env` file for development and in the workflow file for the [working branch](https://github.com/BigSamu/OpenSearch-Dashboards/blob/feat/chanelog_project/.github/workflows/parse_changelog_workflow.yml) of OpenSearch-Dashboard for the changelog project pass the deployment URL as a parameter.

The setup for the GITHUB_APP_DOMAIN should be finally as follows:

```js
export const GITHUB_APP_DOMAIN = process.env.ENV
  ? process.env.INPUT_GITHUB_APP_DOMAIN
  : process.env.GITHUB_APP_DOMAIN;
```

With the workflow file [parse_changelog_workflow.yml](https://github.com/BigSamu/OpenSearch-Dashboards/blob/feat/chanelog_project/.github/workflows/parse_changelog_workflow.yml) passing an input as follows:

```yml
# Other code...
with:
     token: ${{secrets.GITHUB_TOKEN}}
     github_app_domain: 'https://open-search-changeset-bot.vercel.app'
     changeset_path: changelogs/fragments
``` 
 
And in the `.env` variable for the Reusable Workflow for [OpenSearch_Parse_Changelog_Action](https://github.com/BigSamu/OpenSearch_Parse_Changelog_Action/tree/main), adding the tunnel domain for working in dev mode with the Github App

```
GITHUB_APP_DOMAIN='<your-tunnel-domain>'
```
